### ISSUE TITLE
Notifications_test is branching on the err being nil to handling failed transmission versus when non-nil

### ISSUE THREAD

**Issue by mkbhanda** [edgexfoundry/go-mod-core-contracts#112]
/github.com/edgexfoundry/go-mod-core-contracts/models/notifications_test.go

Line 39:
if err == nil {
handleFailedTransmission(t)
}

Line 55:
if err == nil {
handleFailedTransmission(t)
}

**Comment by michaelestrin** [comment]
Closed due to inactivity.
