### ISSUE TITLE
Create new fields in ResourceOperation

### ISSUE THREAD

**Issue by iain-anderson** [edgexfoundry/go-mod-core-contracts#114]
As discussed in Device Services WG 24th Jun
New fields:

- DeviceCommand   (json:"deviceCommand")
- DeviceResource    (json:"deviceResource")

"Object" to be marked as deprecated (replaced by DeviceResource)
"Resource" to be marked as deprecated (replaced by DeviceCommand)
Arrangements to be made in marshaling to duplicate values for compatibility purposes.

**Comment by tsconn23** [comment]
> Arrangements to be made in marshaling to duplicate values for compatibility purposes.

Just to unpack this a little bit for further clarity -- The [ResourceOperation model](https://github.com/edgexfoundry/go-mod-core-contracts/blob/master/models/resourceoperation.go) needs to implement the Validator interface. Validation in this case will handle a check on each of the deprecated properties to see if they have a value. If not, validation should look to the new property and assign its value to the old property.

- Object (old) --> DeviceResource (new)
- Resource (old) --> DeviceCommand (new)

The reason for this is that we want to change the Device SDK to use the new properties exclusively. However the core services need to be backward compatible and in a given deployment may still be looking at the old properties. For example if a Fuji device service is calling an Edinburgh core service, the core service won't be aware of these new properties.

As described above, we'll mark the old properties as `deprecated` and then remove them in the Geneva release.

**Comment by cloudxxx8** [comment]
I thought the new properties are higher priority, so the logic in validation should be:
check whether the new property exist, if true, assign the value to the old property, else, read the old property and assign the value to the new property.  After validation, the old and new properties contain the same value in either case.  Thus, it could work with the Device Services from edinburgh and fuiji.
The edinburgh Device Services use the old properties, and the fuiji ones use the new properties.

@tsconn23 and @iain-anderson , if you agree with the logic process, I could help open the PR in go-core-contract and device-sdk-go both.
