### ISSUE TITLE
Issue warning when LogLevel is incorrectly specified

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/go-mod-core-contracts#115]
From https://github.com/edgexfoundry/device-sdk-go/issues/325, there is not a warning issued for invalid LogLevel settings:

https://github.com/edgexfoundry/go-mod-core-contracts/blob/ab099800f5bf055fb95c35604f41f5c22f3c7434/clients/logger/logger.go#L69-L72

I think there should be some kind of warning issued when it is set to an invalid value.

**Comment by tsconn23** [comment]
Do you mean "warning" as in a `logger.Warn("improper log level set, defaulted to Info")` or an error being thrown and handled by the caller? I'm assuming the former but wanted to clarify.

**Comment by anonymouse64** [comment]
Yeah, since the code is able to "handle" the error by selecting a default issuing a warning through `logger.Warn` seems sensible to me

**Comment by michaelestrin** [comment]
Closed for inactivity.
