### ISSUE TITLE
Several types String methods always include fields, even when empty

### ISSUE THREAD

**Issue by brandonforster** [edgexfoundry/go-mod-core-contracts#143]
Follow up from #139 

The following types always include fields in their `String` method, even when empty:

- Action
- CallbackAlert
- CommandResponse
- DescribedObject
- Device
- Get
- IntervalAction
- Interval
- ProfileProperty
- ProvisionWatcher
- Put
- ResourceOperation
- Units
- ValueDescriptor

However, for some of these, an empty object is an invalid state. Should we implement expected String behavior for all of these, only the ones where an empty object is a valid state, or none of them?

**Comment by michaelestrin** [comment]
Added @jdharms.  

Goal is to push through this work as quickly as possible and have this issue completed before Fuji code freeze.  Discussed with @tsconn23 last night; based on pattern established with #163, please now submit 6-8 models per PR.

@jdharms -- move to this when your security work has been completed (@tingyuz indicated yesterday that your security contributions would likely wrap up today or tomorrow).  Review comments made in original abandoned PR #157, study changes to Addressable model made in #163, and reach out directly if you have questions.
