### ISSUE TITLE
Tests should run cleanly when passed the "-race" argument

### ISSUE THREAD

**Issue by jdharms** [edgexfoundry/go-mod-core-contracts#146]
To ensure our tests (and to some extent production code) are reliable, we should be running unit tests with the -race argument in the Makefile. Currently, the tests fail when run in this mode.

Failing tests: 
* TestNewEventClientWithConsul()
* TestNewReadingClientWithConsul()
* TestNewValueDescriptorClientWithConsul()
* TestNewAddressableClientWithConsul()
* TestNewCommandClientWithConsul()
* TestNewDeviceServiceClientWithConsul()
* TestNewDeviceClientWithConsul()
* TestNewProvisionWatcherClientWithConsul()

These tests should succeed when passed -race, and then we should add -race to the test target in our Makefile.

**Comment by brandonforster** [comment]
Per discussion on DevOps WG call on 27 February, this has been rescoped from Geneva to Hanoi so that DevOps can address some underlying build concerns.

**Comment by tonyespy** [comment]
@brandonforster can you describe the build concerns that are blocking this? While working on the discovery PR for device-sdk-go, I noticed that running the example simple-device throws all kinds of errors when built and run w/-race.

**Comment by brandonforster** [comment]
> @brandonforster can you describe the build concerns that are blocking this? While working on the discovery PR for device-sdk-go, I noticed that running the example simple-device throws all kinds of errors when built and run w/-race.

`-race` requires CGO, which most of our build environments lack. They're using Alpine Linux, which has a stripped down version of the Go compiler without C extensions. Adding this will require replacing Alpine, which is a Hanoi scoped item.

This should have been recorded in the DevOps minutes for that meeting.

**Comment by jpwhitemn** [comment]
DevOps addressed
