### ISSUE TITLE
Remove deprecated fields in DeviceProfile components

### ISSUE THREAD

**Issue by iain-anderson** [edgexfoundry/go-mod-core-contracts#189]
PropertyValue: Precision, Size
ResourceOperation: Resource, Object

**Comment by cloudxxx8** [comment]
@tsconn23 if we will have v1 and partial v2 API both in Geneva (as v1.2 you mentioned in the mail), we would need a way to handle two versions of data models in `go-mod-core-contracts`
These fields should not be removed until the appropriate approach is in place.

**Comment by cloudxxx8** [comment]
this issue has been resolved in V2
