### ISSUE TITLE
Current model of Readings does not provide Datatype of Value

### ISSUE THREAD

**Issue by ashubhatt** [edgexfoundry/go-mod-core-contracts#193]
The [Reading structure ](https://github.com/edgexfoundry/go-mod-core-contracts/blob/892c76594632f1888adc7f8949698420825669b9/models/reading.go#L22) is missing a field for Datatype of Sensor Value. Presently all the Values are converted to String format for each Reading. But the **datatype** of value **is not retained**, and I **cannot** find any way to **recover the datatype of Value**.

Proposed Solution:
A new field can be introduced in the structure to retain the datatype.  For this purpose, we can reuse the [ValueType](https://github.com/edgexfoundry/device-sdk-go/blob/0749bf2bbbaf424e6ee3aee44608466ddf380fa6/pkg/models/commandvalue.go#L24) enum from Device SDK Go.

PS: Let me know if there is a way to recover datatype or the thought-process behind not retaining the Value's datatype in the first place.

*** Solution [discussed ](https://github.com/edgexfoundry/go-mod-core-contracts/issues/193#issuecomment-593481163)in Device Services WG 2-Mar-2020 ***

**Comment by tsconn23** [comment]
This was discussed in the Core Working Group today (27-Feb-2020) and will be taken up for the Geneva release. Awaiting further discussion in the Device Services Working Group on Monday (2-Mar-2020) at which point it should get scheduled.

**Comment by cloudxxx8** [comment]
@tsconn23 may we name this field `dataType` instead of `type`?
We have a customer also needs this field in north bound, so we have implemented it in our commercial version based on fuji.  The field name is `dataType` in Reading.
If you agree, we can take this job to open a PR in this repository.

**Comment by tsconn23** [comment]
Discussed on Device Service WG 2-Mar-2020

- Will also add 'MediaType' property as string. Should only be included if the reading is binary.
- 'FloatEncoding' property as string
