### ISSUE TITLE
Implement strategy pattern on retry algorithm in registry implementation of URLClient

### ISSUE THREAD

**Issue by brandonforster** [edgexfoundry/go-mod-core-contracts#204]
While working #196, it was decided that the retry algorithm should be customizable and configurable for different use cases. This issue will implement a new interface and contain three strategies for the algorithm:

1. the current retry algorithm
2. a "No Retry" algorithm that fails fast and does not attempt to retry
3. a null implementation intended for clients that know they will use a URLClient implementation that does not use the retry algorithm. This implementation should panic on all calls to it.

Additionally, the unit tests for the registry client should be rewritten to be deterministic and rely on new methods written for the strategies to ensure that the strategy is executed when expected.

**Comment by michaelestrin** [comment]
> 3\. a null implementation intended for clients that know they will use a URLClient implementation that does not use the retry algorithm. This implementation should panic on all calls to it.

Discussed but shouldn't be part of the deliverable.
