### ISSUE TITLE
Migrate Data Type Enumerations from device-sdk-go

### ISSUE THREAD

**Issue by AnthonyMBonafide** [edgexfoundry/go-mod-core-contracts#225]
As we are implementing the ideas presented in the [Array Datatypes ADR](https://github.com/edgexfoundry/edgex-docs/blob/master/docs_src/design/adr/device-service/0002-Array-Datatypes.md), we need to move the data type enumerations so that it is in a common place. The data types we are looking to move are:
https://github.com/edgexfoundry/device-sdk-go/blob/9e6d46c2b077c5ce04ff29192bd4c5718c8c2e91/pkg/models/commandvalue.go#L26-L66

along with any supporting functionality associated with the enumerations. 

We will have to consolidate the types that are coming from `device-sdk-go` and the existing data types found here:
https://github.com/edgexfoundry/go-mod-core-contracts/blob/2ecd085bbca6ad6bda9224ce78a5545e05826953/models/reading.go#L22-L35

Please refer to the meeting notes and recording from the [March 26 Core Working Group Meeting](https://wiki.edgexfoundry.org/display/FA/Core+Working+Group) for more details

**Comment by iain-anderson** [comment]
@AnthonyMBonafide  #228  closes this?

**Comment by cloudxxx8** [comment]
we should be able to close this issue because it has been moved to https://github.com/edgexfoundry/device-sdk-go/issues/468

**Comment by tonyespy** [comment]
@jpwhitemn per @cloudxxx8's earlier comment, we should close this out as there's an open device-sdk-go which already covers it.

**Comment by cloudxxx8** [comment]
agree
