### ISSUE TITLE
ProvisionWatcher embeds DeviceProfile and DeviceService

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/go-mod-core-contracts#226]
The `ProvistionWatcher` model embeds both a `DeviceProfile` and `DeviceService` (as does a Device). These should be changed to strings, and should just contain the names of both objects, as there's no reason the device SDKs need the entire models when performing discovery.

**Note** - I looked, but couldn't find the related issue to address this in `Device`. We probably need to wait for Hanio to make the change for `Device`, as it would cause a breaking API change. The same can't really be said for `ProvisionWatcher`s as they haven't been used for anything until this release (Geneva).

**Comment by jpwhitemn** [comment]
Per Tony's comment on #826, is this Geneva or Hanoi?

**Comment by tonyespy** [comment]
@jpwhitemn As we haven't yet implemented V2 watchers this issue really only applies to 1.x, so my vote would be to close this out, as this would be a breaking change to V1.

@cloudxxx8 we should just ensure that when we do implement provision watchers for V2, we make sure to only include device profile and device service names vs. embedding the objects.

**Comment by cloudxxx8** [comment]
@tonyespy sure, that's the plan.
> 
> @cloudxxx8 we should just ensure that when we do implement provision watchers for V2, we make sure to only include device profile and device service names vs. embedding the objects.

**Comment by cloudxxx8** [comment]
V2 design has addressed this issue, please see
https://github.com/edgexfoundry/edgex-go/pull/2982
https://github.com/edgexfoundry/go-mod-core-contracts/issues/371
