### ISSUE TITLE
Add quality of the value field in the reading model

### ISSUE THREAD

**Issue by worldmaomao** [edgexfoundry/go-mod-core-contracts#229]
Hello everyone,
As you know, many industry protocals have quality field for value from device.
So have you ever consider that adding quality  field in the reading model.
Thank you!

**Comment by tsconn23** [comment]
Please take this to edexfoundry.slack.com

**Comment by jpwhitemn** [comment]
@worldmaomao - if you don't want to enter into our EdgeX Slack channels, please feel free to reach out to me with your enhancement suggestion.  If you can, please provide as much detail as possible and importantly, give us some idea of your use case.  Even if it is not implemented soon, if the TSC considers it a valid request, we can add it to the backlog.  Email me at jim@iotechsys.com
