### ISSUE TITLE
Refactor BaseObject

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/go-mod-core-contracts#26]
The `BaseObject` type embedded in 19 of the models currently needs both consistent handling and a rename. If it is to be kept, then:

- it needs to be introduced into all models that have the associated fields in their signature -- `Origin`,`Created`,`Modified`. These are all defined as `int64` and represent timestamps.
- the name `BaseObject` needs to be replaced with something more meaningful to its presence. As described above, all of the fields are timestamps. Therefore I suggest we call the type `Timestamps`.

The name `BaseObject` is also objectionable because it suggests inheritance over composition. Go's embedded types are not a form of inheritance, they are instead composition. FWIW, this name is a holdover from the [original Java](https://github.com/edgexfoundry/core-domain/blob/master/src/main/java/org/edgexfoundry/domain/common/BaseObject.java) --> Go conversion.

------------------------------------------------------------------------------
As an aside, it's worth noting here that I have previously been advocating the removal of `BaseObject` and instead placing its properties directly inline into each type that currently uses it. I'm rethinking that position due to the following resources:
- The discussion in [this thread](https://github.com/golang/go/issues/22013) 
- From "[The Go Programming Language](https://www.amazon.com/Programming-Language-Addison-Wesley-Professional-Computing/dp/0134190440)" book -- pp. 104-107 (Struct Embedding and Anonymous Fields), pp.161-164 (Composing Types by Struct Embedding)

Besides the name, I didn't like that the `BaseObject` type was merely a property bag. It didn't define any particular behavior or responsibility. To me that was a code smell. However if you look at the book examples above, this is exactly the kind of types they use to compose the `ColoredPoint` scenario. In some ways, I am still uncomfortable with a hierarchical organization of types for very little semantic meaning. But if we rename `BaseObject` to something more indicative of what its role is (like `Timestamps`) then I think it's more palatable to retain.

**Comment by AnthonyMBonafide** [comment]
I have taken a look into this and created a PR. Going off of the references mentioned above, I think  it is desirable to simply rename the type from `BaseObject` to `Timestamps`.

**Comment by brandonforster** [comment]
closed via #57
