### ISSUE TITLE
Create tag property / field on Event

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/go-mod-core-contracts#270]
Per the architect's meeting of July 20th and Core WG meeting of 8/20/20, it was decided that EdgeX should provide the means to attribute all event/readings to a gateway, host platform or originating EdgeX instance.  Therefore, each Event object should have a "tags" field (and array of strings) that allow for the platform to place identifying information into the tags field that help attribute the event/reading(s) to the host.

How and when the EdgeX instance places platform identifying information in "tags" is still being worked out.  For the initial implementation, the application services will offer an optional enrichment function that will use configuration data to populate the tags field of the event before is exported out of EdgeX.

See these documents for more details:
-  https://wiki.edgexfoundry.org/download/attachments/37912817/7-20-Architecture%20Monthly%20Meeting%20Minutesg.pdf?version=1&modificationDate=1595268367000&api=v2
-  https://wiki.edgexfoundry.org/download/attachments/329472/CoreWG-AgendaAndMinutes-8-20-20.pdf?version=1&modificationDate=1597953562101&api=v2

**Comment by lenny-intel** [comment]
Is a single tag a simple string like `xyz-1002` or a key/value pair like `gateway-id:xyz-1002`

**Comment by lenny-intel** [comment]
Also, if this is for Hanoi, then it applies to both V1 models and V2 DTOs/models, correct?

**Comment by jpwhitemn** [comment]
Yes on V1 and V2 question.
Per the last architect's meeting, we said that the tags property should be "Should be array of k/v (Maps) or JSON object"
