### ISSUE TITLE
 Core-metadata PUT endpoints for Device Admin/OpState

### ISSUE THREAD

**Issue by nbfhscl** [edgexfoundry/go-mod-core-contracts#272]
refering to [#1361](https://github.com/edgexfoundry/edgex-go/pull/1361), the put endpoints for device admin/opstate in metadata have been revised but not updated [here](https://github.com/edgexfoundry/go-mod-core-contracts/blob/06f35a91c3483fdb0f6c49f522d5f90e47e2d85a/clients/metadata/device.go#L173)

**Comment by difince** [comment]
@cloudxxx8 I would assign this issue to myself if you do not mind

**Comment by cloudxxx8** [comment]
no problem, thanks, @difince
