### ISSUE TITLE
Add full robust validation of Type on V2's PropertyValue

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/go-mod-core-contracts#289]
For V2's PropertyValue, the `Type` property is required, but needs robust validation to insure the value is a valid ValueType.

Also should we rename the `Value` property to be `ValueType` so it is consistent with that used on Readings?

**Comment by tonyespy** [comment]
Changing `Type` to `ValueType` would mean our YAML-based device profiles would also need to be updated. That said, changing it would make it consistent with the [V2 Reading](https://github.com/edgexfoundry/go-mod-core-contracts/blob/master/v2/models/reading.go#L18) model.

Also note a [duplicate issue](https://github.com/edgexfoundry/go-mod-core-contracts/issues/83) (closed) was reported against V1, but never implemented.

**Comment by tonyespy** [comment]
The other thing to note here is that we had a discussion at this week's device services' WG meeting about validation of `[Value]Type` in `PropertyValue` and it was pointed out that the V1 code defined all of the types using CamelCase, whereas the [original device service requirements document](https://wiki.edgexfoundry.org/display/FA/Device+and+Device+SDK+Working+Group?preview=%2F329488%2F46760195%2Fedgex-device-service-requirements-v11.pdf) (v11) and the [V2 Device Services ADR](https://github.com/edgexfoundry/edgex-docs/blob/master/docs_src/design/adr/device-service/0011-DeviceService-Rest-API.md) both specify the Type enums as lowercase strings.

It was suggested during this meeting that maybe we should just handle these values in a case-insensitive manner, and there seemed to be no push back on this suggestion. This can be implemented by using `string.ToUpper|ToLower` functions or just use `string.EqualFold` which implements a more generic Unicode case-folding, which is a more general form of case-insensitivity.

**Note** - [issue #383](https://github.com/edgexfoundry/go-mod-core-contracts/issues/383) advocates for lowercase `valueType` enumerations, however as noted above `ValueType` is a `Reading` field, not a `PropertyValue` field.

**Comment by tonyespy** [comment]
Actually, to since v1 uses CamelCase, it's probably best to do case-insensitive validation of DTOs and `PropertyValue` instances (i.e. when adding or updating a device profile) and convert to the CameCase constants internally, such that any `Readings` produced by a 2.x version of EdgeX produce types that align with 1.x versions of EdgeX.
