### ISSUE TITLE
Add support to get current log level

### ISSUE THREAD

**Issue by ajcasagrande** [edgexfoundry/go-mod-core-contracts#294]
Currently there is support for setting the log level, but there is no support for querying the current log level.

This is very important because in some cases it is preferable to check if Debug logging is enabled before even making the Debug log call because of computations that are performed, like for instance:

```go
if lgr.IsLevelEnabled(models.DebugLog) {
  lgr.Debug(fmt.Sprintf("Average latency: %.2f ms", computeAverageLatency()))
}
```

This is a rudimentary example, but the point is that `computeAverageLatency()` may take a long time to complete, something we would prefer to avoid calling if it is never going to be actually logged.

**Comment by jpwhitemn** [comment]
Do we need this if we have formatted log messages (via #295)?

**Comment by ajcasagrande** [comment]
In my above example, `computeAverageLatency()` would still get called regardless of where the formatting actually happens because it is executed as a pre-requisite to calling the function. The only way around that would be some sort of lambda/clousre that provided deferred execution, but that's not the case here.
```go
lgr.Debugf("Average latency: %.2f ms", computeAverageLatency())
```

At a minimum a simple exposed function to get the private level would suffice: 
_(note for some reason `logLevel` is a pointer so we have to check for `nil` to avoid nil pointer dereference.)_

```go
func (lc edgeXLogger) LogLevel() string {
	if lc.logLevel == nil {
		return "";
	}
	return *lc.logLevel;
}
```

**Comment by lenny-intel** [comment]
Planned for ireland.
