### ISSUE TITLE
Add formatted alternatives to log functions, ie. logger.Infof

### ISSUE THREAD

**Issue by ajcasagrande** [edgexfoundry/go-mod-core-contracts#295]
This could probably be a thing to be done during the work of #246.

I propose that `fmt.Sprintf`-like alternatives be added to the logging functions, like:
```go
func (lc edgeXLogger) Tracef(format string, a ...interface{})
func (lc edgeXLogger) Debugf(format string, a ...interface{})
func (lc edgeXLogger) Infof(format string, a ...interface{})
func (lc edgeXLogger) Warnf(format string, a ...interface{})
func (lc edgeXLogger) Errorf(format string, a ...interface{})
```

For one it would simplify this:
```go
loggingClient.Info(fmt.Sprintf("Starting %s %s ", internal.CoreDataServiceKey, edgex.Version))
```
into this:
```go
loggingClient.Infof("Starting %s %s ", internal.CoreDataServiceKey, edgex.Version)
```

However even more importantly, because the `fmt.Sprintf` is being called by the SDK's code, you can delay the execution of it until **_after_** the [log level check](https://github.com/edgexfoundry/go-mod-core-contracts/blob/b139196b2d205d068909f4e736248de9c8d5224f/clients/logger/logger.go#L162-L170) has been completed. In the case of some heavy formatting calls, this could save some cycles.

```go
lgr.Debug(fmt.Sprintf("%+v", deviceProfile))  // entire deviceProfile struct will be pretty-formatted no matter what
lgr.Debugf("%+v", deviceProfile)              // will only perform the formatting if Debug logging is enabled
```

**Comment by jpwhitemn** [comment]
Ireland Planning Meeting in scope task
