### ISSUE TITLE
V2 API models contain incorrect or empty description

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/go-mod-core-contracts#309]
There are some models with no parameter description, like [deviceresource.go](https://github.com/edgexfoundry/go-mod-core-contracts/blob/master/v2/models/deviceresource.go).
Some models with incorrect descriptions, like `LastReported` in [deviceservice.go](https://github.com/edgexfoundry/go-mod-core-contracts/blob/master/v2/models/deviceservice.go#L16).

**Comment by cloudxxx8** [comment]
@lenny-intel @jpwhitemn @iain-anderson 
We had better put these field description into a single place, such as Swagger file.
In current go source code, some of them contain full description, but some of them don't

Full example
https://github.com/edgexfoundry/go-mod-core-contracts/blob/a48a3cfc95ac7623bae8df3d1eb5020ec58becf8/v2/models/device.go#L8-L25

Incorrect example
https://github.com/edgexfoundry/go-mod-core-contracts/blob/a48a3cfc95ac7623bae8df3d1eb5020ec58becf8/v2/models/deviceservice.go#L16

Not comment example
https://github.com/edgexfoundry/go-mod-core-contracts/blob/a48a3cfc95ac7623bae8df3d1eb5020ec58becf8/v2/models/deviceresource.go#L9-L15

I suggest to remove all them from source code, and only leave the comment if the fields are not the same as DTO.

**Comment by lenny-intel** [comment]
Yes, I like putting the descriptions in only the Swagger and and comment to the structs that says to see swagger for details.
