### ISSUE TITLE
[V2 metadata] Device OperatingState value change

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/go-mod-core-contracts#318]
Discussed in the Device WG meeting on 5th-Oct-2020, we would like to change the enumeration value of OperatingState from Enabled/Disabled to Up/Down/Unknown.

**Comment by cloudxxx8** [comment]
@iain-anderson may we make a decision in the next WG meeting?

**Comment by iain-anderson** [comment]
Rename to UP/DOWN is in scope as per Ireland planning meeting. Are there DSs where we can make a distinction between down and unknown and is it useful to do so?
