### ISSUE TITLE
Add Support For Binary Readings

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/go-mod-core-contracts#32]
Per the Core WG call on 14-Mar-19 we need to start adding support for binary readings as part of the CBOR initiative for Edinburgh release. To that end, the following changes need to be made in the core contracts module.

- Add to ValueDescriptor model
  - "MimeType" property (string)
  - Modify unit tests accordingly
- Add to Reading model
  - "Blob" property ([]byte)
  - Modify unit tests accordingly
- Clients/coredata/event.go
  - The "Add" method should be refactored to look at the incoming context for a `Content-type` header. If found, then send the value through as part of the request. Otherwise default to JSON, which is the current behavior.

Please define a new [constant](https://github.com/edgexfoundry/go-mod-core-contracts/blob/master/clients/constants.go) for the new header value `application/cbor`. This will be usable by any application utilizing the contracts and will avoid naming mismatch issues.

**Comment by lenny-intel** [comment]
I suggest the following Content Type constants to start with : 

- application/json
- application/cbor
- application/xml

**Comment by tsconn23** [comment]
Yes, we already have a couple of those:
https://github.com/edgexfoundry/go-mod-core-contracts/blob/5d775d0480d8908efa18c30cac6dcb87cdc84e37/clients/request.go#L33

**Comment by tonyespy** [comment]
> Per the Core WG call on 14-Mar-19 we need to start adding support for binary readings as part of the CBOR initiative for Edinburgh release. To that end, the following changes need to be made in the core contracts module.
> 
> * Add to ValueDescriptor model
>   
>   * "MimeType" property (string)
>   * Modify unit tests accordingly

I don't like MimeType here as it's a term usually associated with email attachments. I think ContentType is more appropriate, although to make it clear that it just applies binary readings, I suggested "BinaryContentType" in our meeting earlier today.

I also believe that this field needs to be added to PropertyValue, which is what is embedded in each deviceResource, as defined by the device profile. PropertyValue is used to populate the ValueDescriptor.

> * Add to Reading model
>   
>   * "Blob" property ([]byte)

Thoughts on maybe calling this BinaryValue?

>   * Modify unit tests accordingly
> * Clients/coredata/event.go
>   
>   * The "Add" method should be refactored to look at the incoming context for a `Content-type` header. If found, then send the value through as part of the request. Otherwise default to JSON, which is the current behavior.
> 
> Please define a new [constant](https://github.com/edgexfoundry/go-mod-core-contracts/blob/master/clients/constants.go) for the new header value `application/cbor`. This will be usable by any application utilizing the contracts and will avoid naming mismatch issues.

Otherwise looks good to me!

**Comment by tsconn23** [comment]
To @tonyespy's point about the "MIMEType" name I proposed ["MediaType"](https://en.wikipedia.org/wiki/Media_type) and he +1'ed it in Slack, so that's what we're going with.

Also, the field will be moved from `Value Descriptor` to the `ProfileProperty` struct.

For clarity, I am going to restate the entirety of the desired changes here with the above edits applied.

-------
- Add to ProfileProperty model
  - "MediaType" property (string)
  - Modify unit tests accordingly
- Add to Reading model
  - "BinaryValue" property ([]byte)
  - Modify unit tests accordingly
- Clients/coredata/event.go
  - The "Add" method should be refactored to look at the incoming context for a `Content-type` header. If found, then send the value through as part of the request. Otherwise default to JSON, which is the current behavior.

Please define a new [constant](https://github.com/edgexfoundry/go-mod-core-contracts/blob/master/clients/constants.go) for the new header value `application/cbor`. This will be usable by any application utilizing the contracts and will avoid naming mismatch issues.

**Comment by tobiasmo1** [comment]
@tsconn23 @tonyespy I believe we need MediaType in the Reading model but I will confirm with Tony later today.
