### ISSUE TITLE
[V2 metadata] Modified deviceProfile DTO to support PUT API

### ISSUE THREAD

**Issue by weichou1229** [edgexfoundry/go-mod-core-contracts#326]
Since community decide to use the PUT instead of the PATCH operation, so it need to modified the struct and related function.

**Comment by lenny-intel** [comment]
@weichou1229 , @cloudxxx8 , @jpwhitemn ,When was this decided? We had long discussion and design that updates would only have the properties being changed.  Why does using PUT change this?

**Comment by cloudxxx8** [comment]
@lenny-intel we discussed it in one of the Core WG meeting, and Device Profile is the only one exception.  I remember you said it make sense users would like to replace the whole profile, and we do the same thing in upload YAML profile.
Maybe it was my misunderstanding.  Do you think we should provide patch for Device Profile?

**Comment by cloudxxx8** [comment]
On the other hand, the most of the fields in Profile are sub object array, and we need to replace whole array in the current design.  There is no specific value to provide patch.  The better way to provide additional APIs for users to manipulate the sub objects in a profile, for example adding a new device resource into a specific profile.

**Comment by lenny-intel** [comment]
> Do you think we should provide patch for Device Profile?

@cloudxxx8 , Ahh, ok. Remembering now. Sorry for the confusion. And yes, better way in the future is to add APIs to update to sub-portions of the profile. 

I think the Add and Update then become the same. I will comment on the PR. THX!
