### ISSUE TITLE
Add CBOR Conversion to AddEvent

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/go-mod-core-contracts#36]
Pending merge of PR #35.

The [Add() function](https://github.com/edgexfoundry/go-mod-core-contracts/blob/7a2734aa6c016ab61519f629ae24eedac203b52f/clients/coredata/event.go#L133) of event.go within the core-data client should check the incoming Context for a `ContentType` value. If a value is not found, then `ContentTypeJson` should be the default. However if `ContentTypeCbor` is found, then the client should marshal the incoming event as CBOR instead of JSON. This should still allow the client to pass a byte array to the `clients.PostRequest()` method.

The current candidate for accomplishing CBOR marshalling is [ugorji](https://github.com/ugorji/go). This library has no dependencies other than the Go std lib.

**Comment by brandonforster** [comment]
closed via #39
