### ISSUE TITLE
[V2] change "name" property on Reading to resourcename or something more meaningful

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/go-mod-core-contracts#379]
Per Ireland planning meeting, the name property is not meant to name the reading and so it should have a better describing property name such as resourcename

**Comment by lenny-intel** [comment]
This issue is already handled in https://github.com/edgexfoundry/go-mod-core-contracts/issues/370

**Comment by cloudxxx8** [comment]
closed by #374
