### ISSUE TITLE
Consider removal of DeviceService from Device struct

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/go-mod-core-contracts#40]
I recently reported an issue against device-sdk-go that concerned dumping entire objects in non-debug log messages.

The offending log message was actually including the entire state of a Device object, which is enormous! This got me to thinking whether it's actually a good idea for us to be embedding an entire DeviceService in every device as opposed to DeviceService.Name (or ID)? 
Note, this is related to issue #27 which proposes removing DeviceProfile from Device.

**Comment by michaelestrin** [comment]
Closed.  Expect this to be addressed by the [Geneva v2 API](https://github.com/tsconn23/edgex-geneva-api) changes.
