### ISSUE TITLE
[V2 meta] Add ReadingClient

### ISSUE THREAD

**Issue by FelixTing** [edgexfoundry/go-mod-core-contracts#418]
Add V2 ReadingClient for interactions with the V2 Reading endpoint on the Core Data Service.
- [(GET) /reading/all](https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-data/2.x#/default/get_reading_all)
- [(GET) /reading/count](https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-data/2.x#/default/get_reading_count)
- [(GET) /reading/count/device/name/{name}](https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-data/2.x#/default/get_reading_count_device_name__name_)
- [(GET) /reading/device/name/{name}](https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-data/2.x#/default/get_reading_device_name__name_)
- [(GET) /reading/resourceName/{resourceName}](https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-data/2.x#/default/get_reading_resourceName__resourceName_)
- [(GET) /reading/start/{start}/end/{end}](https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-data/2.x#/default/get_reading_start__start__end__end_)

**Comment by cloudxxx8** [comment]
fixed by #419
