### ISSUE TITLE
Create constants for the configuration map

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/go-mod-core-contracts#449]
We need:

- Metadata
- Data
- Primary

They will be used in core-data, core-command, device services, and so on.

**Comment by lenny-intel** [comment]
@cloudxxx8 , could you explain what `configuration map` in more detail?

**Comment by cloudxxx8** [comment]
For example, we have those in the configuration file:

```
[Clients]
  [Clients.Data]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48080

  [Clients.Metadata]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48081
```

Then, we need the constants for configuration map key instead of hardcode
https://github.com/edgexfoundry/edgex-go/blob/48f292ecce04635bad45b2dac08c505f02e60d07/internal/core/data/init.go#L61-L62

**Comment by lenny-intel** [comment]
I agree we should have constants. 
We have this old similar issue (In Icebox) on edgex-go that wants to use the service keys as the constants for the map keys.
https://github.com/edgexfoundry/edgex-go/issues/2424
@jpwhitemn We should discuss this in Core WG meeting

**Comment by cloudxxx8** [comment]
this issue will be discussed in the next architects' meeting

**Comment by jpwhitemn** [comment]
Somewhat related to https://github.com/edgexfoundry/edgex-go/issues/2424

Per the Monthly Architect's meeting of 1/26/21 - it was decided that 
We will use service keys in configuration.toml files 
Service keys are defined in https://github.com/edgexfoundry/go-mod-core-contracts/blob/master/clients/constants.go
