### ISSUE TITLE
[V2] Create factory methods for Request DTOs

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/go-mod-core-contracts#450]
We have factory methods for Response DTOs, and we also need them for Request DTOs.
Those methods should assign the correct ApiVersion.

**Comment by lenny-intel** [comment]
@cloudxxx8, @weichou1229.  IMO, the sub-DTOs also need factory methods like I did with Event and Reading. In this case Device and Update device should have factory methods. These each have fields like ApiVersion, Id, etc that should be auto set by the factory method. The required properties like Name , etc should be parameters to the factory method.

**Comment by cloudxxx8** [comment]
@lenny-intel I just opened a new issue for this.
https://github.com/edgexfoundry/go-mod-core-contracts/issues/499

We can add more when we need them.
