### ISSUE TITLE
[V2] Event DTO needs ToXML() similar to the one for V1 Event model

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/go-mod-core-contracts#455]
Standard XML marshaling doesn't handle the Tags map properly, so the Event DTO needs the ToXML() function similar to the on for the V1 Event model here: https://github.com/edgexfoundry/go-mod-core-contracts/blob/master/models/event.go#L117

**Comment by judehung** [comment]
@lenny-intel Per https://github.com/edgexfoundry/go-mod-core-contracts/blob/master/v2/dtos/event.go#L56, V2 Event DTO actually had implemented `ToXML()`.  Do we still need this issue?

**Comment by lenny-intel** [comment]
Humm, must have missed it when I looked. Nope. Closing this issue. THX!
