### ISSUE TITLE
about Logs

### ISSUE THREAD

**Issue by zhongweibest** [edgexfoundry/go-mod-core-contracts#476]
The current log is continuously output to a single file, which is very unfriendly to view the log. I hope it can be made into a configurable log that is separated by day and size. Thank you

**Comment by lenny-intel** [comment]
@zhongweibest , which environment and release are you running? 
In Geneva, we deprecated logging to file and remote and only log to STDOUT.

Docker the logs for each service (container) are handled separately by Docker and can be view individually via the `docker logs` command
```
Usage:  docker logs [OPTIONS] CONTAINER

Fetch the logs of a container

Options:
      --details        Show extra details provided to logs
  -f, --follow         Follow log output
      --since string   Show logs since timestamp (e.g. 2013-01-02T13:23:37Z) or relative (e.g. 42m for 42 minutes)
  -n, --tail string    Number of lines to show from the end of the logs (default "all")
  -t, --timestamps     Show timestamps
      --until string   Show logs before a timestamp (e.g. 2013-01-02T13:23:37Z) or relative (e.g. 42m for 42 minutes)
```


Snaps uses syslog, which is one large file, but has the `snap logs` command that will filter for a specific service

```
Usage:
  snap logs [logs-OPTIONS] <service>...

The logs command fetches logs of the given services and displays them in
chronological order.

[logs command options]
      -n=              Show only the given number of lines, or 'all'. (default: 10)
      -f               Wait for new lines and print them as they come in.

[logs command arguments]
  <service>:           A service specification, which can be just a snap name (for all services in the snap), or <snap>.<app> for a single service.
```

**Comment by jpwhitemn** [comment]
Closing this issue for lack of additional information.  We can reopen if additional details are provided.
