### ISSUE TITLE
[V2] Rename `Resource` property to `SourceName` in AutoEvents and Commands

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/go-mod-core-contracts#502]
This property can be set to a Resource Name or a Device Command Name, so the property name needs not be so specific.

**Comment by lenny-intel** [comment]
@cloudxxx8 , Command DTO doesn't have `Resource`. Is it implied by the `Name`? Should `Name` be changed to `Source`?
https://github.com/edgexfoundry/go-mod-core-contracts/blob/master/v2/dtos/command.go#L13

**Comment by cloudxxx8** [comment]
@lenny-intel I am thinking whether we should keep `Name` field and add `Source` field in Command DTO/Model.
Command should be human readable if possible, but Device Resource might be "ANALOG_OUTPUT_0".
If `Source` is empty, we can auto-fill out it with the `Name` during unmarshall.
What do you think?

**Comment by cloudxxx8** [comment]
@lenny-intel @jpwhitemn we need to discuss in the Core WG meeting to decide whether we should make the change in CoreCommand section.

**Comment by cloudxxx8** [comment]
Should we use "SourceName" in auto event because it's "SourceName" in event route, not "Source"

**Comment by lenny-intel** [comment]
> Should we use "SourceName" in auto event because it's "SourceName" in event route, not "Source"

I am good with `SourceName`

**Comment by cloudxxx8** [comment]
fixed by #524
