### ISSUE TITLE
Change AutoEvent Frequency to Interval

### ISSUE THREAD

**Issue by iain-anderson** [edgexfoundry/go-mod-core-contracts#51]
As per device services WG discussion on 3/25, the use of frequency in AutoEvents as they stand is inconvenient.
Replace Frequency with an Interval field, with string type.
The format of this field is to be an unsigned integer followed by a unit which may be "ms", "s", "m" or "h" representing milliseconds, seconds, minutes or hours. Eg, "100ms", "24h"

**Comment by cloudxxx8** [comment]
@iain-anderson I has opened the issue and the PR just merged
https://github.com/edgexfoundry/go-mod-core-contracts/pull/50

**Comment by cloudxxx8** [comment]
please close this issue if you see the PR looks good to you

**Comment by iain-anderson** [comment]
please update godoc to indicate more restricted supported format, as above
