### ISSUE TITLE
[V2 DeviceProfile] - Add GetResource() to DeviceProfile Client

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/go-mod-core-contracts#532]
Once new Core Metadata API is ready the DeviceProfile Client needs new the  GetResource() method.

This method should cache the resources rather the making REST request every time.

**Comment by cloudxxx8** [comment]
@lenny-intel may we not deal with cache for now?  there is no mechanism to notify the client library whether the profile is removed or modified.

**Comment by lenny-intel** [comment]
@cloudxxx8 , we previously agreed that this `notify` was not needed.

**Comment by weichou1229** [comment]
> we previously agreed that this notify was not needed 

@lenny-intel But it should be a bug if we return the wrong resource from the cache.

**Comment by cloudxxx8** [comment]
@lenny-intel if we want to make cache, it should be a general mechanism for all the query client

**Comment by lenny-intel** [comment]
@cloudxxx8 , I disagree. This is the one query that has a use case for a cache and we all ready discussed and agreed to this.

**Comment by cloudxxx8** [comment]
sorry, I really forgot this discussion. we will add the cache tomorrow.
however, it would become a mandatory cache.  I still thought the cache responsibility is under the user of client library, not client library itself.
we might at least implement a "CleanCache" function in this client library.

**Comment by lenny-intel** [comment]
> I still thought the cache responsibility is under the user of client library, not client library itself.

We agreed it should be here so it doesn't have to be duplicated by the user services (App services & Kuiper, etc). 


> we might at least implement a "CleanCache" function in this client library.

I am ok with this, not sure when the user services would know to call it.
