### ISSUE TITLE
[V2] Set apiVersion to optional in normal DTOs, except for requestDTOs and EventDTO

### ISSUE THREAD

**Issue by weichou1229** [edgexfoundry/go-mod-core-contracts#537]
Per working group decision 
> Versionable -required on request/response objects and Event (because App Service can receive just an Event) DTO; for other objects, version is optional

see https://wiki.edgexfoundry.org/display/FA/Core+Working+Group?preview=/329472/60784641/CoreWG-AgendaAndMinutes-3-3-2021.pdf

- Remove the required validation tag from apiVersion.
- Check the requestDTOs and EventDTO which should contains valid api version

**Comment by lenny-intel** [comment]
Now that we have had some time to see how this is working, maybe best to focus on having ApiVersion only on top level DTOs (i.e. Request/Response DTOs)  and sub-DTOS that can be received by client w/o a parent Request/Response DTO (i.e. Event DTO). The other DTOs are just composite DTOs, so as we have seen it is redundant to have ApiVersion if the a parent DTO already has it.

So my suggestion now is to remove ApiVersion from DTOs that are not one of the following?

- Request
- Response
- Event

@cloudxxx8 , @jpwhitemn Thoughts?

**Comment by cloudxxx8** [comment]
@lenny-intel I would like to also re-visit the reason we keep ApiVersion in Event.
May we always use AddEventRequest when sending Event to App Service in V2?

**Comment by lenny-intel** [comment]
@cloudxxx8 , the Event DTO is what is exported to external destinations. Having the ApiVersion on Event is  important if that end point has to support existing V1 deployments as the V2 deployments come on-line.

**Comment by cloudxxx8** [comment]
@lenny-intel I understand now.  In this case, we can implement it as your suggestion.

**Comment by weichou1229** [comment]
@lenny-intel I removed the ApiVersion from normal DTOs except event and reading. Could you help review the PR https://github.com/edgexfoundry/go-mod-core-contracts/pull/538?
