### ISSUE TITLE
[V2] Add CBOR support in the Event client library

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/go-mod-core-contracts#543]
The logic of handling CBOR Event should be moved from device-sdk-go to contract client library.

**Comment by lenny-intel** [comment]
Also, please add use of  `experimental`  environment variable `EDGEX_ENCODE_ALL_EVENTS_CBOR` that if `true` all events are encoded as CBOR, not just ones with `binary` readings . Default is false if environment variable not explicitly set to `true` .
