### ISSUE TITLE
[v1] Reading: Bypass validation in subsequent UnmarshalJSON calls

### ISSUE THREAD

**Issue by pshirali** [edgexfoundry/go-mod-core-contracts#585]
Tested on [models/reading.go](https://github.com/edgexfoundry/go-mod-core-contracts/blob/master/models/reading.go) (master) at which is at commit [e04bdb8](https://github.com/edgexfoundry/go-mod-core-contracts/commit/e04bdb85cb3f6698d322d9ad8ef46356830a106f) from 19th June 2020

**Sample test code:**
```
func TestReadingRevalidation(t *testing.T) {
	r := Reading{
		Name: "Test",
		Value: "123",
		ValueType: ValueTypeFloat32,
		FloatEncoding: "float32",
	}

	var u string

	u = `{"name": "UpdatedName"}`
	r.UnmarshalJSON([]byte(u))        // call UnmarshalJSON with a valid JSON to set `isValidated`
	if _, e := r.Validate(); e != nil { t.Fail() }

	// fmt.Println("-------before-------")
	// fmt.Println(r.String())
        // PRINTS: {"name":"UpdatedName","value":"123","valueType":"Float32","floatEncoding":"float32"}

	u = `{"name": "", "value": "", "valueType": "", "floatEncoding": ""}`
	if e := r.UnmarshalJSON([]byte(u)); e != nil { t.Fail() }
	if _, e := r.Validate(); e != nil {
		fmt.Println(e)
		t.Fail()
	}

	// fmt.Println("-------after-------")
	// fmt.Println(r.String())
        // PRINTS: {}
}
```

`Reading.UnmarshalJSON` performs minimal checks (Example `!= nil`) before populating new values from a JSON into a `Reading`. This method ends with a call to `Validate()`, which stores the validation result in `isValidated`

The `Validate` method has the following shortcut to skip validation if `isValidated` is set:
```
	// Shortcut if Reading has already been validated
	if r.isValidated {
		return true, nil
	}
```

This allows the following behaviour:
1. A `Reading` can be updated with a JSON having values which satisfy a validation. This sets the `isValidated` flag.
2. Subsequently, the `Reading` can be updated with a JSON having invalid (empty) values. As the `UnmarshalJSON` method updates the `Reading` first and then validates, the `Reading` can be updated into an invalid state. The validation call returns through the shortcut as the `isValidated` flag is already set.

In the sample test:
1. A `Reading` is composed, and updated with a JSON that passes validation
2. Then it is updated with a JSON which has empty strings as values (invalid as per `Validate`). This call succeeds.
3. The output `r.String()` returns an empty map `{}`

**Comment by cloudxxx8** [comment]
@pshirali thanks for reporting this issue.  it looks like this issue doesn't exist in V2.
by the logical design, Reading is an immutable object, so we didn't consider the update scenario.
also, we won't have any patch release in V1 unless we found out any serious bug.

**Comment by lenny-intel** [comment]
@cloudxxx8 , We can now close this since it was only in V1?

**Comment by pshirali** [comment]
@lenny-intel @cloudxxx8 . Closing this issue. Thanks for the information :)
