### ISSUE TITLE
Protocol properties have typed values

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/go-mod-core-contracts#592]
Issue was brought up in Core WG as it relates to attributes in the device profiles.  The decision of 4/22/21 core working group meeting was to move to proper JSON typing.  It was confirmed that the TOML parsing and Redis persistence could handle this for device profile attributes.  It was also explored to move protocol properties in this same direction, but because provision watcher requires support for regular expressions (which needs to be a string) this was a larger lift with potential issues.

In the future, we want to explore this for protocol properties as well.  This is likely going to be a non-backward compatible change and would have to be a part of a major version.

Device Service WG to explore this a bit.

**Comment by judehung** [comment]
@jpwhitemn @lenny-intel @cloudxxx8 I took some time to investigate this request, and below is my two cents:
```
type Device struct {
	Protocols      map[string]ProtocolProperties `json:"protocols" validate:"required,gt=0"`
}
type ProtocolProperties map[string]string
```
Per current implementation as shown above, the protocols field is in the type of `map[string]map[string]string`.  To make protocol properties support typed values, IMHO, the first level of `map[string]` is redundant and could be ditched.  I'd suggest to simply revise device model/dto to struct like below:

```
type Device struct {
	Protocols      ProtocolProperties `json:"protocols" validate:"required,gt=0"`
}
type ProtocolProperties map[string]any
```
To make ProvisionWatcher still support regular expression to filter device during auto discovery, the map key of [Identifier](https://github.com/edgexfoundry/go-mod-core-contracts/blob/main/models/provisionwatcher.go#L16) can be [GJSONPath](https://github.com/tidwall/gjson#path-syntax) used to locate the correct element as defined in the Protocols.  For example, a provision watcher with following identifiers definition:
```
"identifiers": {
  "tcp.address":"simple[0-9]+",
  "tcp.port":"3[0-9]{2}",
  "udp.port":"514",
}
```
can be used to accept device with following protocols definition:
```
"protocols": {
  "tcp": {
    "address": "simple01",
    "port": "300"
  },
  "udp": {
    "port": "514"
  },
},
```
For this to work, we will have to introduce a third party library  [GJSONPath](https://github.com/tidwall/gjson#path-syntax).  Please kindly let me know if my idea could be a potential solution to support protocol properties with typed values.

**Comment by cloudxxx8** [comment]
@iain-anderson for awareness

**Comment by cloudxxx8** [comment]
@iain-anderson could you put this in the Device Service WG meeting next week?  If we don't implement this issue in 3.0, we have to wait until 4.0.  I will continue the discussion in the Core WG meeting.

**Comment by iain-anderson** [comment]
* I'd prefer to leave the top-level map in place, and just change `ProtocolProperties` to `map[string]any`
* As per the WG meeting on 27th Feb, the regex in the PW should match against the natural string representation of the property. Thus, `"tcp.port":"3[0-9]{2}"` should match a property of `"port": 300` for the `tcp` protocol

**Comment by cloudxxx8** [comment]
Thank, @iain-anderson , we will start the implemenation.
Also, provision watcher will validate the regular expression by convert the protocol properties to the string value.
