### ISSUE TITLE
[V2] Rename the Frequency field in AutoEvent

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/go-mod-core-contracts#609]
It is actually an "Interval", not "Frequency", so I suggest to rename it to "Interval"

**Comment by hahattan** [comment]
Another field that might need renaming as well:
https://github.com/edgexfoundry/go-mod-core-contracts/blob/3e69df61d12908c9f1be535e4d71be1fabedaaf4/v2/dtos/interval.go#L20

**Comment by jpwhitemn** [comment]
Agreed - per Core WG 5/13/21 meeting
