### ISSUE TITLE
Proposal -- Core-data.AddEvent() to Receive Byte Array

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/go-mod-core-contracts#62]
1.) Add new method to EventClient interface
     EncodeEvent(e models.Event) ([]byte, error)
2.) Modify EventClient.Add([]byte, Context) (string, error)

Based on discussion around this flow https://github.com/edgexfoundry/device-sdk-go/issues/233

**Comment by andresrinivasan** [comment]
I read through [edgexfoundry/device-sdk-go#233](https://github.com/edgexfoundry/device-sdk-go/issues/233) and I'm not following how this proposal addresses the issue. Can you elaborate a bit more?

**Comment by tonyespy** [comment]
If I'm interpreting @tsconn23's description, a client wishing to push an Event to Core Data would call the EventClient.EncodeEvent() method to delegate the encoding to the EventClient, then instead if passing an Event to EventClient.Add, it would pass an already encoded Event as a byte array.

**Comment by tsconn23** [comment]
@tonyespy @tobiasmo1 I think I'm going to add another method to the EventClient for the Add. In testing, it's extremely convenient to be able to issue an AddEvent via POST containing JSON. That path would continue to work as it does today, and then I would provide another method `EventClient.AddBytes([]byte, Context) (string, error)`.

Let me know if you have objections.
