### ISSUE TITLE
Change type of Units within models/ProfileProperty to string

### ISSUE THREAD

**Issue by iain-anderson** [edgexfoundry/go-mod-core-contracts#64]
(as discussed dev svcs wg 4-8-19).
Remove models/Units.

**Comment by tsconn23** [comment]
@iain-anderson @tonyespy I relistened to the call to refresh my memory on this. I believe we landed in a different spot than just removing `Units` and changing the property's type to `string`. At first, the proposal was to change `ProfileProperty.Units` to type `string`. But then, the discussion went further suggesting `Units` should actually be a property on `PropertyValue`. In that case, my question would be why have a separation between `ProfileProperty` and `PropertyValue`? After all, `ProfileProperty` will now have only one property which is `PropertyValue`. This says to me they're equivalent. In that case we should eliminate `ProfileProperty` as well, consolidating all of this onto the `PropertyValue` struct. The [DeviceResource.Properties](https://github.com/edgexfoundry/go-mod-core-contracts/blob/ab099800f5bf055fb95c35604f41f5c22f3c7434/models/deviceresource.go#L26) member would change its type to PropertyValue. This would affect the DeviceProfile YAML, etc, as @cloudxxx8 pointed out on the call.

Thoughts?

**Comment by iain-anderson** [comment]
So,

- DeviceResource.Properties becomes a PropertyValue
- Add field PropertyValue.Units (string)
- Remove Units struct
- Remove ProfileProperty struct

I'd be in favor.

**Comment by cloudxxx8** [comment]
@tsconn23 , I listen to the core WG meeting recording on Nov-21, and this issue is what @tonyespy mentioned in the meeting.  For your information.  I believe we could achieve this in Geneva.

From

```
deviceResources:
  -
    name: "LineFrequency"
    description: "Line frequency setting for metering: 50=50 Hz, 60=60Hz"
    attributes:
      { primaryTable: "HOLDING_REGISTERS", startingAddress: "4609" }
    properties:
      value:
        { type: "UINT16", readWrite: "R", scale: "1"}
      units:
        { type: "String", readWrite: "R", defaultValue: "Hz"}
```
To

```
deviceResources:
  -
    name: "LineFrequency"
    description: "Line frequency setting for metering: 50=50 Hz, 60=60Hz"
    attributes:
      { primaryTable: "HOLDING_REGISTERS", startingAddress: "4609" }
    properties:
      value:
        { type: "UINT16", readWrite: "R", scale: "1", units: "Hz"}
```

**Comment by cloudxxx8** [comment]
In this case, we can also eliminate the `value` level here, such as:
```
deviceResources:
  -
    name: "LineFrequency"
    description: "Line frequency setting for metering: 50=50 Hz, 60=60Hz"
    attributes:
      { primaryTable: "HOLDING_REGISTERS", startingAddress: "4609" }
    propertyValue:
      { type: "UINT16", readWrite: "R", scale: "1", units: "Hz"}
```

**Comment by cloudxxx8** [comment]
Oh, it is basically fit what @iain-anderson designed

> So,
> 
> * DeviceResource.Properties becomes a PropertyValue
> * Add field PropertyValue.Units (string)
> * Remove Units struct
> * Remove ProfileProperty struct
> 
> I'd be in favor.

**Comment by tonyespy** [comment]
I'm closing this issue as it's been resolved as part of our V2 API work.

For reference, the V2 [DeviceResource](https://github.com/edgexfoundry/go-mod-core-contracts/blob/master/v2/models/deviceresource.go) and [PropertyValue](https://github.com/edgexfoundry/go-mod-core-contracts/blob/master/v2/models/propertyvalue.go) models.
