### ISSUE TITLE
missing requestBody in dtos/models.Address(RESTAddress)

### ISSUE THREAD

**Issue by gao270615179** [edgexfoundry/go-mod-core-contracts#649]
intervalAction api need the requestBody for HTTP POST

**Comment by weichou1229** [comment]
You can use the `content` as the requestBody for support-scheduler.
https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/support-scheduler/2.0.0#/default/post_intervalaction
For example:
```
[
  {
    "apiVersion":"v2",
    "action": {
        "name": "daily-action",
        "intervalName": "20s",
        "content": "Hello world!",
        "contentType": "text/plain",
        "address":{
            ...
        },
        "adminState":"UNLOCKED"
    }
  }
]
```

**Comment by cloudxxx8** [comment]
another issue opened to update the API document to remove requestBody from RESTAddress
https://github.com/edgexfoundry/edgex-go/issues/3629

**Comment by gao270615179** [comment]
I will try it, thanks!
