### ISSUE TITLE
Use generic interface in the Event Tagging value

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/go-mod-core-contracts#661]
currently the type of Event Tag is `map[string]string`.  I propose to change it to `map[string]interface` to meet more user requirement.
The string can still be used in the Tag.  It's backward compatible.

For example, one of our customer want to tag GPS in the Event, and the current usage looks like the following:
```
        "latitude": "{\"degree\": 25.0, \"minute\": 1.0, \"second\": 26.6268000000062}",
        "longitude": "{\"degree\": 121.0, \"minute\": 31.0, \"second\": 19.600799999980154}"
```

By using the generic interface, it can be:
```
        "latitude": {
            "degrees": 25.0,
            "minute": 1.0,
            "second": 26.6268000000062
        },
        "longitude": {
            "degree": 121.0, 
            "minute": 31.0, 
            "second": 19.600799999980154
        }
```

**Comment by lenny-intel** [comment]
This would be a breaking change.

**Comment by cloudxxx8** [comment]
@lenny-intel which part will be broken?  the string tags can still be used from the API point of view.

**Comment by lenny-intel** [comment]
@cloudxxx8,  The marshaled JSON will be different, I think. Can you confirm that if a string value is used, that the marshaled JSON is the same as it is today.

**Comment by cloudxxx8** [comment]
@lenny-intel yes, we have verified it.  the content is totally the same as it is today.

**Comment by lenny-intel** [comment]
> yes, we have verified it. the content is totally the same as it is today.

Great! I am ok with it as a minor enhancement. :-)

**Comment by cloudxxx8** [comment]
here is an example to show the concept
https://play.golang.org/p/Pk4cHWvI5mA
