### ISSUE TITLE
Create AdminState and OperatingState Request Types

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/go-mod-core-contracts#67]
Changes are required to facilitate the functionality described in the following edgex-go issue
https://github.com/edgexfoundry/edgex-go/issues/1244

This issue will give us the opportunity to introduce functional "request types" into our contracts -- that is, request models that are specific to a particular API endpoint rather than general models which are utilized in various ways for various endpoints. Our current contract models were originally state models within edgex-go. They have been refactored out into their own module now, which is good, but we need to go further so that requests become expressions of intent and support encapsulated validation (per https://github.com/edgexfoundry/go-mod-core-contracts/issues/66).

An example of the above, albeit for a different use case, can be found in the following feature branch.
https://github.com/tsconn23/go-mod-core-contracts/tree/marshal_bug/requests/provision_watcher

Utilizing the package naming [best practices](https://blog.golang.org/package-names), I would suggest creating a `requests` package at the same level as `models` and `clients`. Then underneath that, create a package structure like the following

`states`
- `admin`
- `operating`

The `admin` and `operating` packages above should each contain an `update.go` wherein the respective `UpdateRequest` is defined. The request's sole member would be either `models/OperatingState` or `models/AdminState` so that JSON marshaling will create a request that looks like this:
`{"adminState":"unlocked"}`
`{"operatingState":"disabled"}`

There should also be tests, as in the example branch, but we'll need to see how the timing works out between this issue and #66 which is implementing a new comprehensive model validation scheme. In effect, the work of #66 (which you can see in the feature branch linked in the comments there) will allow these new request types to call Validate() on their respective `AdminState` or `OperatingState` members. If the work on this effort completes first, we may just write the tests as part of #66.

**Comment by brandonforster** [comment]
closed via #69 (nice)

**Comment by brandonforster** [comment]
Closed again via #73
