### ISSUE TITLE
HTTP REST Address should support PATCH method

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/go-mod-core-contracts#685]
We missed `PATCH` method in REST Address DTO, and it should be supported

https://github.com/edgexfoundry/go-mod-core-contracts/blob/9a919a9c23a2e7c41df7b3126a828f9573f06b54/dtos/address.go#L57

**Comment by jpwhitemn** [comment]
@cloudxxx8  - can you provide some details on what this impacts (Scheduler, notifications???).

**Comment by cloudxxx8** [comment]
This RESTAddress struct DTO is for the general REST usage.  It contains `HTTPMethod` field, and we set the validation to make sure the value was limited to `'GET' 'HEAD' 'POST' 'PUT' 'DELETE' 'TRACE' 'CONNECT'`.
However, `PATCH` is also a valid value for `HTTPMethod`, and we missed it when we created this struct.

Currently, the `Subscription` object in Notifications Service and `IntervalAction` object in Scheduler Service contain this struct.
Notifications Service can use REST channel to send out HTTP requests, and IntervalAction can also send out the HTTP requests periodically (according to `Interval`).
Without this fix, the users would see HTTP 400 when they create `Subscription` and `IntervalAction` with HTTP `PATCH` method.

**Comment by JamesKButcher** [comment]
Note this relates to the user's ability to invoke REST PATCH operations on their OWN notifications as opposed to the EdgeX API itself. 

We agreed during the Core WG call today (Dec 2nd) that this is not critical and does not warrant a new release on its own.  Has been added to the "Jakarta Issues" board to be kept track of and released should any critical issues lead to a new Jakarta sub-release.

**Comment by cloudxxx8** [comment]
also fixed in Jakarta branch
