### ISSUE TITLE
Add ServiceName to PingResponse

### ISSUE THREAD

**Issue by AlexCuse** [edgexfoundry/go-mod-core-contracts#696]
For easier debugging at command line.

**Comment by cloudxxx8** [comment]
#695 includes the public API breaking change, so the PR should be reverted

**Comment by AlexCuse** [comment]
Can you provide more detail on the breaking change @cloudxxx8 - I would think if this is a breaking change for all of them if it is for the config response but maybe I am missing some usage.

**Comment by cloudxxx8** [comment]
I replied it here https://github.com/edgexfoundry/go-mod-core-contracts/pull/695#discussion_r792788583 , but we can close this issue if it has been considered.
