### ISSUE TITLE
Command Client missing capability to passes additional query parameters for Get command

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/go-mod-core-contracts#713]
IssueGetCommandByName() doesn't have a parameter for addition query parameters.

Need to add new method `IssueGetCommandByNameWithQueryParms` to allows the user query parameters to be added to the Get command request.

**Comment by hahattan** [comment]
https://github.com/edgexfoundry/go-mod-core-contracts/blob/ca0d31f1868e8ae5e56182402117b42d78f9484f/clients/interfaces/command.go#L28

Can we update this method signature to be more general:
```IssueGetCommandByName(ctx context.Context, deviceName string, commandName string, queryParams map[string]string)```

**Comment by lenny-intel** [comment]
@hahattan,  That would be a breaking change since these clients are used by custom application services.
