### ISSUE TITLE
Create request removes/ignores existing baseUrl path

### ISSUE THREAD

**Issue by ajcasagrande** [edgexfoundry/go-mod-core-contracts#719]
```go
createRequest(ctx, http.MethodDelete, "http://localhost:9000/api/v2/foo", "/bar", nil)
```
becomes
```
http://localhost:9000/bar
```
but should be
```
http://localhost:9000/api/v2/foo/bar
```

https://github.com/edgexfoundry/go-mod-core-contracts/blob/dc8509e3bb4ced693c324e05c1091825c4529801/clients/http/utils/common.go#L68-L73

https://github.com/edgexfoundry/go-mod-core-contracts/blob/dc8509e3bb4ced693c324e05c1091825c4529801/clients/http/utils/common.go#L85-L90

**Comment by cloudxxx8** [comment]
it's an internal helper function, and it meets our original usage design
the third argument, `baseUrl` should only contain host name and port, and all the path should be in the forth argument- `requestPath`

**Comment by lenny-intel** [comment]
@ajcasagrande are you good with closing this as a question answered?

**Comment by ajcasagrande** [comment]
It depends on how you look at it. For me personally, I feel it can be a source of bugs later on when a developer goes to use it and does not realize the limitations. At a minimum I would recommend documenting that, but at that point why not just fix the code?

**Comment by ajcasagrande** [comment]
The fix is simple really:

```go
u.Path = requestPath
```
becomes

```go
// preserve the original path while appending the request path
u.Path = path.Join(u.Path, requestPath)
```

**Comment by lenny-intel** [comment]
> but at that point why not just fix the code?

Because it isn't a bug. 
@cloudxxx8 comment.
> it's an internal helper function, and it meets our original usage design
> the third argument, `baseUrl` should only contain host name and port, and all the path should be in the forth argument- `requestPath`

Where are you exposed to this?

**Comment by ajcasagrande** [comment]
@lenny-intel It is an exported function in a non-internal package and therefore cannot technically be called an internal function, but I get that is the intent of it. And I disagree that it is not a bug. Sure, maybe the current code does not use/abuse the function in this way, but can you guarantee no one will ever try and use it like I have?

We currently are using it in the Camera Example App: https://github.com/edgexfoundry/edgex-examples/blob/main/application-services/custom/camera-management/appcamera/util.go#L54-L70
(we never fully got around to removing those kind of calls)

An overly simplified analogy would be this: Imagine it was an `add(int, int)` function, except that the function was only ever intended to be used with positive integers, and everything below `0` is treated as `0`. So `add(-5, 5)` returns `0+5 => 5`. Bug or not a bug?

Well, there are two scenarios:
1. Maybe that is your intent and you _want_ `add(-5, 5)` to equal `5`. 
> OK alright, in that case just make it obvious that is the intent through code documentation.

2. You never planned/intended on someone calling it with a negative number, and your code base only ever calls it with positive integers.
> In this case it is a bug waiting to happen and should be fixed.

@cloudxxx8's comment leads me to believe it more likely aligns with scenario 2.

**Comment by lenny-intel** [comment]
Ok, I see how the exposed function is being used and the parameters are a bit ambiguous. 

@cloudxxx8 , are you ok with @ajcasagrande 's suggested enhancement to this function?
> ```go
> // preserve the original path while appending the request path
> u.Path = path.Join(u.Path, requestPath)
> ```
I don't see that this will break our code and it make it more flexible on how it is used.

**Comment by cloudxxx8** [comment]
ok, it won't break the existing client usage and looks reasonable
