### ISSUE TITLE
CommandClient mock was not regenerated

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/go-mod-core-contracts#729]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]
CommandClient mock

### Is this a regression?

No/Yes ;-) 

### Description and Minimal Reproduction [**REQUIRED**]

CommandClient mock is missing mock for new `IssueGetCommandByNameWithQueryParams` API

**Comment by weichou1229** [comment]
Added the mock client.

**Comment by cloudxxx8** [comment]
fixed in https://github.com/edgexfoundry/go-mod-core-contracts/pull/731
