### ISSUE TITLE
Optionally exclude validator from build

### ISSUE THREAD

**Issue by hahattan** [edgexfoundry/go-mod-core-contracts#743]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]
 go-mod-core-contracts

### Description [**REQUIRED**]
The validator dependency is adding ~2MB memory footprint for each service:
https://github.com/edgexfoundry/go-mod-core-contracts/blob/eaba535fcbb4638da054880ae7188e155fae9055/common/validator.go#L44-L52
But not all of them are actually using it.

It would be nice to be able to build service without this dependency.

### Describe the solution you'd like
A `no_dto_validator` build flag and corresponding no-op code for the factory seem ideal this would make it easy to produce lighter builds.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by cloudxxx8** [comment]
fixed by #744
