### ISSUE TITLE
[EdgeX 3.0] Device Service model improvement

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/go-mod-core-contracts#771]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

 This feature request is for core-metadata

### Description [**REQUIRED**]
This is issue is opened for discussing the Device Service model improvment in v3.0.

### Describe the solution you'd like
The first suggestion is to remove `LastConnected` and `LastReported `

**Comment by lenny-intel** [comment]
Yes, we agreed that we would replace these with metrics.
