### ISSUE TITLE
[EdgeX 3.0] Provision Watcher model improvement

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/go-mod-core-contracts#772]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

 This feature request is for core-metadata

### Description [**REQUIRED**]
This is issue is opened for discussing the Provision Watcher model improvment in v3.0.

### Describe the solution you'd like
The first suggestion is to modify type of the `Identifiers` to `map[string][]string`, which is the same as the `BlockingIdentifiers`

**Comment by cloudxxx8** [comment]
Another suggestion is to add an extendable field in this object:
`Properties map[string]interface`
For example, the Device Service can support `DeviceNameTemplate` to allow users to define the generated device name.

**Comment by judehung** [comment]
> ### Describe the solution you'd like
> The first suggestion is to modify type of the `Identifiers` to `map[string][]string`, which is the same as the `BlockingIdentifiers`

For the type change on PW's Identifiers, we will address it in #592.  For this #772, we will simply add an extendable field `Properties map[string]any` into ProvisionWatcher dto/model.
