### ISSUE TITLE
Generate service clients using a code generator tool

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/go-mod-core-contracts#777]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]
github.com/edgexfoundry/go-mod-core-contracts/main/clients

### Description [**REQUIRED**]
Code in https://github.com/edgexfoundry/go-mod-core-contracts/blob/main/clients is hand-coded

### Describe the solution you'd like
Code should be auto-generated from swagger or open API generators, such as https://github.com/deepmap/oapi-codegen

**Comment by jumpingliu** [comment]
close this for it's a breaking change

**Comment by cloudxxx8** [comment]
It could be a breaking change for all the client users.
Decided in Core WG 12-DEC-2023.  Since we don't change the API frequently, we have already made all the clients work, the future new API may be messaging base intead of REST, we won't spend time on investigating the client code generation.
