### ISSUE TITLE
AdminState naming in ProvisionWatcher

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/go-mod-core-contracts#813]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

 This feature request is for core-metadata

### Description [**REQUIRED**]
In ProvisionWatcher, there is an `adminState` field, but it's not the adminState of ProvisionWatcher.
The `adminState` here will be assigned to the discovered Devices `adminState`.  The naming is easily cause confusion. 

### Describe the solution you'd like
I suggest to add another field `deviceAdminState` to serve the same purpose, and the original `adminState` should belong to the ProvisionWatcher.  Device SDK should also be modified to skip the ProvisionWatcher which adminState is `LOCKED`

**Comment by cloudxxx8** [comment]
@iain-anderson do you agree with this proposed change?

**Comment by iain-anderson** [comment]
Suggest creating a new structure to hold the fields which are to be assigned on the new device - profileName, adminState, autoEvents, serviceName. Then the PW would have a member `deviceFields` or whatever
