### ISSUE TITLE
Modify the data type of max and min in Value Properties to float64

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/go-mod-core-contracts#816]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

 This feature request is for core-metadata

### Description [**REQUIRED**]
We have the Profile model change in
https://github.com/edgexfoundry/go-mod-core-contracts/issues/770
The change of max and min are missing, and they should be numeric value

**Comment by cloudxxx8** [comment]
@lenny-intel @iain-anderson after more investigation, @hahattan noticed the min and max default value will be 0 in golang, if we change it to float64.  It will cause the incorrect evaluation.

Thus, we decided to revert this change for now.

**Comment by iain-anderson** [comment]
Can it work if you make them *float64 and check for nil pointers?
