### ISSUE TITLE
ValueDescriptor should validate its "Type" field

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/go-mod-core-contracts#82]
There is currently no validation of the Type field of a ValueDescriptor.
We should add validation logic which enforces that type can only be one of the following values:

 * bool
 * string
 * int8|int16|int32|int64
 * uint8|uint16|uint32|uint64
 * float32|float64
 * binary

**Comment by tsconn23** [comment]
Additional details -- The [ValueDescriptor model](https://github.com/edgexfoundry/go-mod-core-contracts/blob/master/models/value-descriptor.go) should implement the Validator interface and then check whether the value of `Type` is one of those shown above. If not, validation should throw an error. Please add a unit test for this behavior.

For extra credit, change the name of the file to `value_descriptor.go` (replace hyphen with underscore). Same goes for the test file.

**Comment by jpwhitemn** [comment]
@tsconn23 @tonyespy - still a Fuji release item?  Label Geneva?

**Comment by tonyespy** [comment]
I'm closing this as it was never implemented for V1, and `ValueDescriptor` has not been carried over for the EdgeX V2 API, so this is no longer applicable.
