### ISSUE TITLE
Modify the numeric data type in Value Properties to pointer

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/go-mod-core-contracts#821]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: core-metadata

### Is this a regression?

 Yes, the previous version in which this bug was not present was: v2.3

### Description and Minimal Reproduction [**REQUIRED**]
Since we modified base, offset, scale in Value Properties to numeric data type, the default values all become 0
https://github.com/edgexfoundry/go-mod-core-contracts/issues/770
The empty value (nil) should be allowed if they are not defined

max and min should also be changed to `*float64`
https://github.com/edgexfoundry/go-mod-core-contracts/issues/816

**Comment by cloudxxx8** [comment]
@jinlinGuan have we implemented all about this issue?

**Comment by jinlinGuan** [comment]
Yes, this issue can be closed.
