### ISSUE TITLE
PropertyValue should validate its Type field

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/go-mod-core-contracts#83]
There is currently no validation of the Type field of a PropertyValue.
We should add validation logic which enforces that type can only be one of the following values:

 * bool
 * string
 * int8|int16|int32|int64
 * uint8|uint16|uint32|uint64
 * float32|float64
 * binary

**Comment by tsconn23** [comment]
Additional details -- The [PropertyValue model](https://github.com/edgexfoundry/go-mod-core-contracts/blob/master/models/propertyvalue.go) should implement the Validator interface and then check whether the value of `Type` is one of those shown above. If not, validation should throw an error. Please add a unit test for this behavior.

For extra credit, change the name of the file to `property_value.go`. Same goes for the test file.

**Comment by jpwhitemn** [comment]
@tonyespy @tsconn23 - still a Fuji release item?  Label Geneva?

**Comment by tonyespy** [comment]
I'm closing this as it deals with the V1 REST API, and there's an [identical issue](https://github.com/edgexfoundry/go-mod-core-contracts/issues/289) open for V2 which will be fixed as part of Ireland.
