### ISSUE TITLE
Validation prevents device services from being referenced by name when part of another object's JSON

### ISSUE THREAD

**Issue by iain-anderson** [edgexfoundry/go-mod-core-contracts#87]
For example, the following request to core-metadata to add a device fails because there is no OperatingState given for the device service:
```
curl -d '{"profile":{"name":"Example Sensor"},"service":{"name":"device-template"},"lastConnected":0,"lastReported":0,"operatingState":"ENABLED","adminState":"UNLOCKED","protocols":{"Other":{"Port":"502","Address":"someSensorEndpoint"}},"name":"TemplateDevice","description":"An Example Template Device","origin":0}' -X POST 0:48081/api/v1/device
```

**Comment by iain-anderson** [comment]
core-metadata logs
```
level=ERROR ts=2019-05-02T15:23:59.724796665Z app=edgex-core-metadata source=rest_device.go:61 msg="invalid OperatingState \"\""
```
and returns HTTP 400 with the message
```
invalid OperatingState ""
```

**Comment by tsconn23** [comment]
Related blackbox test PR https://github.com/edgexfoundry/blackbox-testing/pull/207

**Comment by cloudxxx8** [comment]
@tsconn23 this issue is blocking the Device Services working with core-metadata, including the new black box test of virtual device service.  May we merge the fix made by @iain-anderson first?
add @cherrycl , @FelixTing for awareness

**Comment by badboy-huaqiao** [comment]
@iain-anderson @tsconn23 @cloudxxx8 Replace value receiver with pointer receiver can fix this bug.
`func (as *AdminState) Validate() (bool, error) {
	_, found := map[string]AdminState{"LOCKED": Locked, "UNLOCKED": Unlocked}[string(*as)]
	
	return true, nil
}`

**Comment by badboy-huaqiao** [comment]
@iain-anderson @tsconn23 @cloudxxx8 I'm having the same problem. I fix `invalid OperatingState ""`, but the problem with json formatting cascading, however, is that when adding a device, i must specify the address name or id of the device service. Now i can only remove the code to verify the addressable to add the device successfully
