### ISSUE TITLE
Remove the Parameter field from ResourceOperation

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/go-mod-core-contracts#89]
From the discussion in https://github.com/edgexfoundry/device-sdk-go/issues/150, the Parameter field in ResourceOperation is useless now.

**Comment by cloudxxx8** [comment]
@tsconn23 , please help confirm whether I can open PR to remove this field.
Thanks.

**Comment by cloudxxx8** [comment]
add @iain-anderson for awareness

**Comment by cloudxxx8** [comment]
@badboy-huaqiao I thought you are bringing up different topics here.
for the first code section, it has been modified in master branch
https://github.com/edgexfoundry/device-sdk-go/blob/master/internal/handler/command.go#L304-L310

Also, we do support one command for different to retrieve values from a device by identify multiple Resource Operation in one Device Command.  Please see the example:
https://github.com/edgexfoundry/device-modbus-go/blob/master/cmd/res/example/modbus.test.device.profile.yml#L87-L98

It is not related to the "Parameter" field.  What is your suggestion of using this field?

For the third code section, I don't understand the context.  If you believe it's a real issue, please open another issue in edgex-go repository and provide more information and re-create steps.  Thanks.

**Comment by tsconn23** [comment]
For Fuji, recommend we mark this as `deprecated` and then remove during the Geneva dev cycle.

**Comment by cloudxxx8** [comment]
ok, I am fine with that, and I have removed this field from our example profiles in each device service

**Comment by iain-anderson** [comment]
Historically the Parameter has been used as a default value in "set" operations. So if the json payload on a PUT does not contain a value for a particular resource, the contents of the parameter field in the profile is used (or failing that the defaultValue for the device resource itself).

https://github.com/edgexfoundry/device-sdk/blob/8e9ac0bced6463d49fef38c1e5b9c3e55d12056f/src/main/java/org/edgexfoundry/handler/ProtocolHandler.java#L311-L330

I think we should leave Parameter in and implement the defaulting behavior in the set ops

**Comment by cloudxxx8** [comment]
Since the Parameter field is useful now, closing this PR
This issue is adding feature to use use Parameter field
https://github.com/edgexfoundry/device-sdk-go/issues/356
