### ISSUE TITLE
Remove Validation of Reading.Device Property

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/go-mod-core-contracts#96]
Source issue https://github.com/edgexfoundry/device-sdk-go/issues/269

In order to accomplish this, the following validation requirement that a reading must have a Device name assigned has to be relaxed
https://github.com/edgexfoundry/go-mod-core-contracts/blob/b02b9d963a25310697254f12fbd44cff18e10242/models/reading.go#L126

Following from the above, there's already a PR in edgex-go which will assign the Device name from the Event to each reading before persisting to the database.
https://github.com/edgexfoundry/edgex-go/pull/1324/

Once PR #1324 is merged and this issue is addressed, then device-sdk-go https://github.com/edgexfoundry/device-sdk-go/pull/271 should be ready for integration.

**Comment by brandonforster** [comment]
closed via #97
